language: python
branches:
  only:
  - release
  - dev
python:
  - "3.7"

before_install:
  - |
    if [ "$TRAVIS_BRANCH" = "dev" ] && [ "$TRAVIS_EVENT_TYPE" = "push" ]; then
        echo "Push to dev, not running tests until PR"
        exit 0
    else
      echo "Doing the build"
    fi

install:
  - cd ..
  - pip install ./nxt
  - pip install importlib-metadata==4.12
  - pip install twine

script:
  - |
    if [ "$TRAVIS_BRANCH" = "release" ] && [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then
          python -m nxt.cli test
          exit $?
    fi
  - |
    if [ "$TRAVIS_BRANCH" = "release" ] && [ "$TRAVIS_EVENT_TYPE" = "push" ]; then
          python -m nxt.cli exec nxt/build/packaging.nxt -s /make_and_upload
          exit $?
    fi